"""Create user preferences table

Revision ID: 035d719cca29
Revises: 07dbf23186a4
Create Date: 2024-12-21 22:46:50.806414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035d719cca29'
down_revision = '07dbf23186a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dietary_restrictions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cooking_skill_level', sa.String(), nullable=False),
    sa.Column('kitchen_equipment', sa.JSON(), nullable=True),
    sa.Column('favorite_cuisines', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###