"""Add swipe sessions table

Revision ID: 585079022ff4
Revises: d20fa712c916
Create Date: 2025-01-16 15:03:49.522119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585079022ff4'
down_revision = 'd20fa712c916'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swipe_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_weights', sa.JSON(), nullable=True),
    sa.Column('seen_recipes', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swipe_sessions')
    # ### end Alembic commands ###