"""Create chef context table

Revision ID: 6cc796d60c27
Revises: 035d719cca29
Create Date: 2024-12-21 22:56:45.894623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc796d60c27'
down_revision = '035d719cca29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_preferences_id', sa.UUID(), nullable=False),
    sa.Column('current_recipe_id', sa.UUID(), nullable=True),
    sa.Column('current_step', sa.JSON(), nullable=True),
    sa.Column('session_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_preferences_id'], ['user_preferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chef_contexts')
    # ### end Alembic commands ###