"""Add recipe images

Revision ID: 6ceb1a983de6
Revises: 6cc796d60c27
Create Date: 2024-12-21 23:01:59.637921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ceb1a983de6'
down_revision = '6cc796d60c27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('main_image_url', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('step_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'step_images')
    op.drop_column('recipes', 'main_image_url')
    # ### end Alembic commands ###