"""Simplify recipe images to single image_url

Revision ID: 83bd3c06838d
Revises: 6ceb1a983de6
Create Date: 2024-12-21 23:03:01.310443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83bd3c06838d'
down_revision = '6ceb1a983de6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('recipes', 'main_image_url')
    op.drop_column('recipes', 'step_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('step_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('main_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'image_url')
    # ### end Alembic commands ###