"""Update recipe model with multiple images

Revision ID: 8e2ca9a6714d
Revises: 83bd3c06838d
Create Date: 2024-12-30 16:13:29.105600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2ca9a6714d'
down_revision = '83bd3c06838d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('recipes', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'images')
    # ### end Alembic commands ###