"""Simplify recipe model

Revision ID: a40490189860
Revises: 8e2ca9a6714d
Create Date: 2025-01-06 14:48:57.543399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40490189860'
down_revision = '8e2ca9a6714d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('total_time', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('recipes', 'main_ingredient')
    op.drop_column('recipes', 'meal_type')
    op.drop_column('recipes', 'cooking_time')
    op.drop_column('recipes', 'cuisine_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('cuisine_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('cooking_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('meal_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('main_ingredient', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'tags')
    op.drop_column('recipes', 'total_time')
    # ### end Alembic commands ###