"""Add saved recipes table

Revision ID: d20fa712c916
Revises: a40490189860
Create Date: 2025-01-16 14:47:44.016171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20fa712c916'
down_revision = 'a40490189860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###